name: build and push

on: [push]

jobs:
  build:
    runs-on: docker

    steps:
      - name: check out repository code
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.REGISTRY_URL }}/${{ gitea.REPOSITORY }}:latest
